version: 2
updates:
  # Macspark-App (npm)
  - package-ecosystem: "npm"
    directory: "/Macspark-App"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers: ["marco"]
    assignees: ["marco"]
    commit-message:
      prefix: "deps(app)"
    groups:
      react-ecosystem:
        patterns: ["react*", "@types/react*"]
      ai-providers:
        patterns: ["anthropic", "openai", "google-generativeai"]
        
  # Macspark-MCPs (Python)
  - package-ecosystem: "pip"
    directory: "/Macspark-MCPs/mcp_orchestrator"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers: ["marco"]
    assignees: ["marco"]
    commit-message:
      prefix: "deps(mcp)"
    groups:
      ai-providers:
        patterns: ["anthropic", "openai", "google-generativeai", "mistralai", "cohere"]
      dev-tools:
        patterns: ["pytest*", "black", "isort", "flake8", "mypy"]
        
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"