name: CI/CD Pipeline - Agente Facebook v3.0

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        pip install -r scripts/requirements-dev.txt
    
    - name: Lint with pylint
      run: |
        pylint scripts/*.py --fail-under=7.0 || true
      continue-on-error: true
    
    - name: Check formatting with black
      run: |
        black scripts/ --check || true
      continue-on-error: true
    
    - name: Type check with mypy
      run: |
        mypy scripts/ --ignore-missing-imports || true
      continue-on-error: true
    
    - name: Run tests with pytest
      run: |
        pytest tests/test_validate_env.py -v --cov=scripts --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
