version: '3.8'

services:
  superset:
    image: apache/superset:latest
    container_name: superset-marketing
    ports:
      - "8088:8088"
    environment:
      # IMPORTANTE: Trocar este secret key!
      # Gerar novo: openssl rand -base64 42
      - SUPERSET_SECRET_KEY=CHANGE_THIS_TO_RANDOM_SECRET_KEY_GENERATED_WITH_OPENSSL
      
      # Database (usando SQLite interno para simplicidade)
      - SUPERSET_METADATA_DB_URI=sqlite:////app/superset_home/superset.db
      
      # Timezone
      - SUPERSET_TIMEZONE=America/Sao_Paulo
      
      # Admin credentials (trocar após primeiro login!)
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_FIRSTNAME=Admin
      - ADMIN_LASTNAME=User
      
    volumes:
      - superset_home:/app/superset_home
      - ./superset_config.py:/app/pythonpath/superset_config.py:ro
    
    restart: unless-stopped
    
    command: >
      sh -c "
      pip install psycopg2-binary &&
      superset db upgrade &&
      superset fab create-admin 
        --username $${ADMIN_USERNAME} 
        --firstname $${ADMIN_FIRSTNAME} 
        --lastname $${ADMIN_LASTNAME} 
        --email $${ADMIN_EMAIL} 
        --password $${ADMIN_PASSWORD} || true &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload
      "
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  superset_home:
    driver: local

networks:
  default:
    name: marketing-metrics-network

